# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kria_bd/kria_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd || ORIG_REF_NAME==kria_bd} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_3/kria_bd_zynq_ultra_ps_e_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==kria_bd_zynq_ultra_ps_e_0_3} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_axi_intc_0_4/kria_bd_axi_intc_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_4 || ORIG_REF_NAME==kria_bd_axi_intc_0_4} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_clk_wiz_0_5/kria_bd_clk_wiz_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_5 || ORIG_REF_NAME==kria_bd_clk_wiz_0_5} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_proc_sys_reset_0_6/kria_bd_proc_sys_reset_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_6 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_6} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_axi_smc_7/kria_bd_axi_smc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_axi_smc_7 || ORIG_REF_NAME==kria_bd_axi_smc_7} -quiet] -quiet

# Block Designs: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/bd_9880.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_0/bd_9880_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_1/bd_9880_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_2/bd_9880_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_3/bd_9880_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_4/bd_9880_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_5/bd_9880_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_6/bd_9880_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_7/bd_9880_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_8/bd_9880_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_9/bd_9880_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_10/bd_9880_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_11/bd_9880_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_12/bd_9880_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/kria_bd/ip/kria_bd_proc_sys_reset_1_1/kria_bd_proc_sys_reset_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_1 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_1} -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_3/kria_bd_zynq_ultra_ps_e_0_3_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_3/kria_bd_zynq_ultra_ps_e_0_3.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_zynq_ultra_ps_e_0_3 || ORIG_REF_NAME==kria_bd_zynq_ultra_ps_e_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_4/kria_bd_axi_intc_0_4.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_4 || ORIG_REF_NAME==kria_bd_axi_intc_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_4/kria_bd_axi_intc_0_4_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_4 || ORIG_REF_NAME==kria_bd_axi_intc_0_4} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_4/kria_bd_axi_intc_0_4_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_5/kria_bd_clk_wiz_0_5_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_5 || ORIG_REF_NAME==kria_bd_clk_wiz_0_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_5/kria_bd_clk_wiz_0_5.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_5 || ORIG_REF_NAME==kria_bd_clk_wiz_0_5} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_5/kria_bd_clk_wiz_0_5_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_0_6/kria_bd_proc_sys_reset_0_6_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_6 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_0_6/kria_bd_proc_sys_reset_0_6.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_6 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_1/bd_9880_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_1/bd_9880_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_5/bd_9880_s00a2s_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_6/bd_9880_sarn_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_7/bd_9880_srn_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_8/bd_9880_sawn_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_9/bd_9880_swn_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_10/bd_9880_sbn_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/bd_0/ip/ip_11/bd_9880_m00s2a_0_ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/ooc.xdc

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_smc_7/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_axi_smc_7 || ORIG_REF_NAME==kria_bd_axi_smc_7} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_1_1/kria_bd_proc_sys_reset_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_1 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_1_1/kria_bd_proc_sys_reset_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_1 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/randy/projects/Kria_KR260/Kria_KR260.gen/sources_1/bd/kria_bd/kria_bd_ooc.xdc
