# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/default.xdc

# Block Designs: bd/kria_starter_kit/kria_starter_kit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit || ORIG_REF_NAME==kria_starter_kit} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_zynq_ultra_ps_e_0_0/kria_starter_kit_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_starter_kit_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_starter_kit/ip/kria_starter_kit_xlslice_0_0/kria_starter_kit_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_starter_kit_xlslice_0_0 || ORIG_REF_NAME==kria_starter_kit_xlslice_0_0} -quiet] -quiet

# XDC: /scratch/jenkins-BUILDS-hw_designs_builds-2024.2_amd-yocto-hw-platforms-95_kr260_base/kria_base/k26/kr260_base/hw_project/kr260_base/kr260_base.gen/sources_1/bd/kria_starter_kit/kria_starter_kit_ooc.xdc
